FROM ghcr.io/projectbluefin/dakota@sha256:06f5511bca3ce5b44cb9069c2f34d77823b300ae7aada9e177075e986103b28e
RUN echo 'add_dracutmodules+=" lvm "' > /etc/dracut.conf.d/50-lvm.conf && \
    dracut --regenerate-all --force
